import React, { useState } from 'react';
import { CheckCircle2, Phone, UserRound, X } from 'lucide-react';
import { useExpense } from '../context/ExpenseContext';

export const ProfileModal: React.FC = () => {
  const { currentUser, isProfileModalOpen, setIsProfileModalOpen, updateMyPhone, logout } = useExpense();
  const [phone, setPhone] = useState(currentUser.phone); const [message, setMessage] = useState('');
  if (!isProfileModalOpen) return null;
  const save = (event: React.FormEvent) => { event.preventDefault(); const result = updateMyPhone(phone); setMessage(result.message || (result.success ? 'Phone number updated.' : '')); };
  return <div onClick={() => setIsProfileModalOpen(false)} className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md"><div onClick={(event) => event.stopPropagation()} className="w-full max-w-md rounded-3xl bg-slate-900 border border-slate-700 shadow-2xl overflow-hidden"><div className="p-6 flex justify-between items-start bg-gradient-to-r from-indigo-500/15 to-emerald-500/10 border-b border-slate-800"><div className="flex gap-3"><div className={`w-12 h-12 rounded-2xl flex items-center justify-center font-black ${currentUser.avatar}`}>{currentUser.name.slice(0, 2).toUpperCase()}</div><div><p className="text-[10px] font-black uppercase tracking-wider text-emerald-400">My profile</p><h2 className="font-black text-xl text-white">{currentUser.name}</h2><p className="text-xs text-slate-400">Manage your account details</p></div></div><button onClick={() => setIsProfileModalOpen(false)} className="p-2 text-slate-400 hover:text-white"><X className="w-5 h-5"/></button></div><form onSubmit={save} className="p-6 space-y-5"><div><label className="text-xs font-bold text-slate-300 flex items-center gap-1.5"><UserRound className="w-3.5 h-3.5"/> Username</label><div className="mt-1.5 p-3 rounded-xl bg-slate-950 border border-slate-800 text-sm font-bold text-slate-300">{currentUser.name}</div></div><div><label className="text-xs font-bold text-slate-300 flex items-center gap-1.5"><Phone className="w-3.5 h-3.5"/> Phone number *</label><input required value={phone} onChange={(event) => setPhone(event.target.value)} className="mt-1.5 w-full p-3 rounded-xl bg-slate-950 border border-slate-700 text-white text-sm" /></div>{message && <p className="flex gap-2 text-xs text-emerald-400"><CheckCircle2 className="w-4 h-4"/>{message}</p>}<button className="w-full p-3 rounded-xl bg-emerald-500 text-slate-950 text-sm font-black">Save phone number</button></form><div className="p-4 border-t border-slate-800"><button onClick={() => { setIsProfileModalOpen(false); logout(); }} className="w-full text-xs font-bold text-rose-400">Log out</button></div></div></div>;
};
