import React, { useState } from 'react';
import { Check, Copy, DoorOpen, Plus, Users, X } from 'lucide-react';
import { useExpense } from '../context/ExpenseContext';

export const RoomSelector: React.FC = () => {
  const { rooms, activeRoom, setActiveRoomId, createRoom, joinRoom } = useExpense();
  const [open, setOpen] = useState(false); const [name, setName] = useState(''); const [code, setCode] = useState(''); const [joinCode, setJoinCode] = useState(''); const [message, setMessage] = useState('');
  const create = (e: React.FormEvent) => { e.preventDefault(); const res = createRoom(name, code); setMessage(res.message || (res.success ? 'Room created.' : '')); if (res.success) { setName(''); setCode(''); setOpen(false); } };
  const join = (e: React.FormEvent) => { e.preventDefault(); const res = joinRoom(joinCode); setMessage(res.message || (res.success ? 'Joined room.' : '')); if (res.success) { setJoinCode(''); setOpen(false); } };
  const copyCode = async () => { await navigator.clipboard?.writeText(activeRoom.code); setMessage('Room code copied.'); };
  return <div className="relative flex items-stretch rounded-xl bg-indigo-500/10 border border-indigo-500/30 text-indigo-300">
    <button onClick={() => setOpen((value) => !value)} title="Manage rooms" className="flex items-center gap-2 px-3 py-2 text-xs font-bold min-w-0"><DoorOpen className="w-4 h-4 shrink-0"/><span className="hidden md:inline truncate">{activeRoom.name}</span><span className="font-mono whitespace-nowrap">🔑 {activeRoom.code}</span></button>
    <button onClick={copyCode} title="Copy room code" aria-label="Copy room code" className="px-2 border-l border-indigo-500/30 hover:bg-indigo-500/15 rounded-r-xl"><Copy className="w-3.5 h-3.5"/></button>
    {open && <><button aria-label="Close room menu" onClick={() => setOpen(false)} className="fixed inset-0 z-40 cursor-default"/><div className="absolute right-0 top-12 z-50 w-[min(20rem,calc(100vw-1.5rem))] p-4 rounded-2xl bg-slate-900 border border-slate-700 shadow-2xl space-y-4"><div className="flex justify-between items-center"><p className="text-xs font-black text-white">My Rooms</p><button onClick={() => setOpen(false)} aria-label="Close room menu" className="p-1 text-slate-400 hover:text-white"><X className="w-4 h-4"/></button></div>{rooms.length > 0 ? rooms.map((room) => <button key={room.id} onClick={() => { setActiveRoomId(room.id); setOpen(false); }} className="w-full flex justify-between items-center p-3 rounded-xl bg-slate-950 hover:bg-slate-800 text-left"><span><span className="block text-xs font-bold text-white">{room.name}</span><span className="text-[10px] text-emerald-400 font-mono">🔑 {room.code}</span></span>{room.id === activeRoom.id && <Check className="w-4 h-4 text-emerald-400"/>}</button>) : <p className="text-xs text-slate-400">No rooms yet. Create one or join with a code.</p>}<form onSubmit={create} className="pt-3 border-t border-slate-800 space-y-2"><p className="text-[11px] font-bold text-slate-400"><Plus className="inline w-3 h-3"/> Create a room</p><input required value={name} onChange={(e) => setName(e.target.value)} placeholder="Room name" className="w-full p-2 rounded-lg bg-slate-950 border border-slate-700 text-xs text-white"/><input value={code} onChange={(e) => setCode(e.target.value)} placeholder="Room code (auto if empty)" className="w-full p-2 rounded-lg bg-slate-950 border border-slate-700 text-xs text-white"/><button className="w-full p-2 rounded-lg bg-emerald-500 text-slate-950 text-xs font-black">Create room</button></form><form onSubmit={join} className="pt-3 border-t border-slate-800 space-y-2"><p className="text-[11px] font-bold text-slate-400"><Users className="inline w-3 h-3"/> Join with code</p><input required value={joinCode} onChange={(e) => setJoinCode(e.target.value)} placeholder="e.g. FLAT302" className="w-full p-2 rounded-lg bg-slate-950 border border-slate-700 text-xs text-white"/><button className="w-full p-2 rounded-lg bg-indigo-500 text-white text-xs font-black">Join room</button></form>{message && <p className="text-[11px] text-amber-300">{message}</p>}</div></>}
  </div>;
};
